package:
  name: slapi
  version: "0.0.2"

source:
  git_rev: v0.0.2
  git_url: https://github.com/pythonflaskserverapps/slapi.git

requirements:
  build:
    - python
    - setuptools
  run:
    - urllib3[secure]==1.24.1
    - websocket-client==0.54.0

test:
  imports:
    - slapi

about:
  home: https://github.com/pythonflaskserverapps/slapi
  license: MIT
  license_file: LICENSE
